import { MachineType } from "./types";
import { MaintenanceType } from "./types";
import { InventoryItemType } from "./types";

export const MACHINES: MachineType[]= [
  {
    name: "Computador A",
    type: "Desktop",
    model: "X1000",
    manufactureDate: "2023-01-15",
    serialNumber: "SN123456789",
    location: "Sala 101",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Impressora B",
    type: "Laser",
    model: "P2000",
    manufactureDate: "2022-07-20",
    serialNumber: "SN987654321",
    location: "Sala 102",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Laptop C",
    type: "Notebook",
    model: "L500",
    manufactureDate: "2023-03-10",
    serialNumber: "SN112233445",
    location: "Sala 103",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Projetor D",
    type: "Multimedia",
    model: "PJ700",
    manufactureDate: "2021-11-05",
    serialNumber: "SN556677889",
    location: "Sala de Reuniões",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Servidor E",
    type: "Rackmount",
    model: "SRX100",
    manufactureDate: "2022-02-28",
    serialNumber: "SN998877665",
    location: "Sala de Servidores",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Monitor F",
    type: "LCD",
    model: "M3000",
    manufactureDate: "2021-09-12",
    serialNumber: "SN223344556",
    location: "Sala 104",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Scanner G",
    type: "Flatbed",
    model: "SC200",
    manufactureDate: "2023-06-18",
    serialNumber: "SN778899001",
    location: "Sala 105",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Teclado H",
    type: "USB",
    model: "TK400",
    manufactureDate: "2023-05-25",
    serialNumber: "SN123456001",
    location: "Sala 106",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Mouse I",
    type: "Optical",
    model: "MS500",
    manufactureDate: "2023-04-15",
    serialNumber: "SN654321002",
    location: "Sala 107",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Telefone J",
    type: "IP",
    model: "T1000",
    manufactureDate: "2022-12-01",
    serialNumber: "SN789456003",
    location: "Sala 108",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Modem K",
    type: "Fiber Optic",
    model: "MD800",
    manufactureDate: "2023-02-15",
    serialNumber: "SN456789004",
    location: "Sala 109",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Roteador L",
    type: "Wireless",
    model: "RT500",
    manufactureDate: "2023-01-10",
    serialNumber: "SN321654005",
    location: "Sala 110",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Câmera M",
    type: "Security",
    model: "CM600",
    manufactureDate: "2022-08-30",
    serialNumber: "SN987123006",
    location: "Corredor Principal",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Equipamento de Áudio N",
    type: "Audio",
    model: "AU900",
    manufactureDate: "2022-10-10",
    serialNumber: "SN654987007",
    location: "Sala de Conferências",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Impressora O",
    type: "Inkjet",
    model: "IP800",
    manufactureDate: "2023-03-22",
    serialNumber: "SN456789008",
    location: "Sala 111",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Armazenamento P",
    type: "NAS",
    model: "ST2000",
    manufactureDate: "2021-05-17",
    serialNumber: "SN123789009",
    location: "Sala de TI",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
];


export const MAINTENANCES: MaintenanceType[] = [
  {
    code: "MT-001",
    title: "Troca de Filtro de Ar",
    description: "Substituir o filtro de ar do sistema de ventilação.",
    type: "preventiva", 
    status: "em andamento",
    requisitionDate: "2024-08-01",
    priority: "alta",
    responsableTeam: "Equipe de Manutenção Geral",
  },
  {
    code: "MT-002",
    title: "Reparo de Vazamento de Água",
    description:
      "Consertar o vazamento identificado na tubulação do segundo andar.",
    type: "corretiva", 
    status: "em andamento",
    requisitionDate: "2024-08-05",
    priority: "média",
    responsableTeam: "Equipe de Hidráulica",
  },
  {
    code: "MT-003",
    title: "Calibração de Equipamentos",
    description:
      "Realizar a calibração dos instrumentos de medição de temperatura.",
    type: "preventiva", 
    status: "em andamento",
    requisitionDate: "2024-08-10",
    priority: "baixa",
    responsableTeam: "Equipe de Instrumentação",
  },
  {
    code: "MT-004",
    title: "Substituição de Motor",
    description:
      "Trocar o motor da máquina de impressão que apresentou falhas constantes.",
    type: "corretiva", 
    status: "em andamento",
    requisitionDate: "2024-08-12",
    priority: "alta",
    responsableTeam: "Equipe de Manutenção de Máquinas",
  },
  {
    code: "MT-005",
    title: "Inspeção de Sistema de Segurança",
    description: "Verificar o funcionamento dos sistemas de câmeras e alarmes.",
    type: "preditiva", 
    status: "em andamento",
    requisitionDate: "2024-08-15",
    priority: "média",
    responsableTeam: "Equipe de Segurança",
  },
];


export const INVENTORY: InventoryItemType[] = [
  {
    id: "1",
    name: "Chave de Fenda",
    type: "ferramenta",
    quantity: 25,
    location: "Depósito A",
    supplier: "Ferramentas X",
    acquisitionDate: "2023-05-10",
    status: "disponível",
  },
  {
    id: "2",
    name: "Parafuso M10",
    type: "peça",
    quantity: 500,
    location: "Depósito B",
    supplier: "Parafusos Y",
    acquisitionDate: "2023-03-12",
    status: "disponível",
  },
  {
    id: "3",
    name: "Martelo",
    type: "ferramenta",
    quantity: 10,
    location: "Oficina 1",
    supplier: "Ferramentas Z",
    acquisitionDate: "2022-11-05",
    status: "em uso",
  },
  {
    id: "4",
    name: "Broca 10mm",
    type: "peça",
    quantity: 100,
    location: "Depósito C",
    supplier: "Fabricação W",
    acquisitionDate: "2023-01-20",
    status: "disponível",
  },
  {
    id: "5",
    name: "Alicate Universal",
    type: "ferramenta",
    quantity: 15,
    location: "Depósito A",
    supplier: "Ferramentas X",
    acquisitionDate: "2023-07-18",
    status: "disponível",
  },
  {
    id: "6",
    name: "Roda Dentada",
    type: "peça",
    quantity: 50,
    location: "Depósito B",
    supplier: "Engrenagens V",
    acquisitionDate: "2022-08-30",
    status: "em manutenção",
  },
  {
    id: "7",
    name: "Chave Inglesa",
    type: "ferramenta",
    quantity: 8,
    location: "Oficina 2",
    supplier: "Ferramentas Z",
    acquisitionDate: "2022-09-10",
    status: "em uso",
  },
  {
    id: "8",
    name: "Buchas de Nylon",
    type: "peça",
    quantity: 200,
    location: "Depósito C",
    supplier: "Fixação Q",
    acquisitionDate: "2023-06-22",
    status: "disponível",
  },
  {
    id: "9",
    name: "Serra Elétrica",
    type: "ferramenta",
    quantity: 5,
    location: "Oficina 3",
    supplier: "Ferramentas X",
    acquisitionDate: "2023-02-14",
    status: "em uso",
  },
  {
    id: "10",
    name: "Cabo de Aço",
    type: "peça",
    quantity: 120,
    location: "Depósito A",
    supplier: "Metais F",
    acquisitionDate: "2023-04-05",
    status: "disponível",
  },
  {
    id: "11",
    name: "Furadeira",
    type: "ferramenta",
    quantity: 12,
    location: "Oficina 1",
    supplier: "Ferramentas W",
    acquisitionDate: "2022-10-01",
    status: "em uso",
  },
  {
    id: "12",
    name: "Mangueira de Borracha",
    type: "peça",
    quantity: 30,
    location: "Depósito B",
    supplier: "Plásticos L",
    acquisitionDate: "2022-12-15",
    status: "em manutenção",
  },
  {
    id: "13",
    name: "Chave Allen",
    type: "ferramenta",
    quantity: 40,
    location: "Depósito A",
    supplier: "Ferramentas Q",
    acquisitionDate: "2023-07-05",
    status: "disponível",
  },
  {
    id: "14",
    name: "Correia Dentada",
    type: "peça",
    quantity: 75,
    location: "Depósito C",
    supplier: "Engrenagens M",
    acquisitionDate: "2023-03-28",
    status: "disponível",
  },
  {
    id: "15",
    name: "Esmerilhadeira",
    type: "ferramenta",
    quantity: 6,
    location: "Oficina 3",
    supplier: "Ferramentas Y",
    acquisitionDate: "2023-05-01",
    status: "em uso",
  },
];
